
---
name: Swift build
on:
  pull_request:
    branches:
      - main
    types: [ opened, edited, reopened, synchronize ]
    paths: 
      - '**.swift'
jobs:
  build:
    name: Swift build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: swift build